// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="overlay_fea_overlay_fea,hls_ip_2021_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=12069,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1831,HLS_SYN_LUT=2679,HLS_VERSION=2021_2}" *)

module overlay_fea (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        length_r,
        kSQI,
        kSQI_ap_vld,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 66'd1;
parameter    ap_ST_fsm_state2 = 66'd2;
parameter    ap_ST_fsm_state3 = 66'd4;
parameter    ap_ST_fsm_state4 = 66'd8;
parameter    ap_ST_fsm_state5 = 66'd16;
parameter    ap_ST_fsm_state6 = 66'd32;
parameter    ap_ST_fsm_state7 = 66'd64;
parameter    ap_ST_fsm_state8 = 66'd128;
parameter    ap_ST_fsm_state9 = 66'd256;
parameter    ap_ST_fsm_state10 = 66'd512;
parameter    ap_ST_fsm_state11 = 66'd1024;
parameter    ap_ST_fsm_state12 = 66'd2048;
parameter    ap_ST_fsm_state13 = 66'd4096;
parameter    ap_ST_fsm_state14 = 66'd8192;
parameter    ap_ST_fsm_state15 = 66'd16384;
parameter    ap_ST_fsm_state16 = 66'd32768;
parameter    ap_ST_fsm_state17 = 66'd65536;
parameter    ap_ST_fsm_state18 = 66'd131072;
parameter    ap_ST_fsm_state19 = 66'd262144;
parameter    ap_ST_fsm_state20 = 66'd524288;
parameter    ap_ST_fsm_state21 = 66'd1048576;
parameter    ap_ST_fsm_state22 = 66'd2097152;
parameter    ap_ST_fsm_state23 = 66'd4194304;
parameter    ap_ST_fsm_state24 = 66'd8388608;
parameter    ap_ST_fsm_state25 = 66'd16777216;
parameter    ap_ST_fsm_state26 = 66'd33554432;
parameter    ap_ST_fsm_state27 = 66'd67108864;
parameter    ap_ST_fsm_state28 = 66'd134217728;
parameter    ap_ST_fsm_state29 = 66'd268435456;
parameter    ap_ST_fsm_state30 = 66'd536870912;
parameter    ap_ST_fsm_state31 = 66'd1073741824;
parameter    ap_ST_fsm_state32 = 66'd2147483648;
parameter    ap_ST_fsm_state33 = 66'd4294967296;
parameter    ap_ST_fsm_state34 = 66'd8589934592;
parameter    ap_ST_fsm_state35 = 66'd17179869184;
parameter    ap_ST_fsm_state36 = 66'd34359738368;
parameter    ap_ST_fsm_state37 = 66'd68719476736;
parameter    ap_ST_fsm_state38 = 66'd137438953472;
parameter    ap_ST_fsm_state39 = 66'd274877906944;
parameter    ap_ST_fsm_state40 = 66'd549755813888;
parameter    ap_ST_fsm_state41 = 66'd1099511627776;
parameter    ap_ST_fsm_state42 = 66'd2199023255552;
parameter    ap_ST_fsm_state43 = 66'd4398046511104;
parameter    ap_ST_fsm_state44 = 66'd8796093022208;
parameter    ap_ST_fsm_state45 = 66'd17592186044416;
parameter    ap_ST_fsm_state46 = 66'd35184372088832;
parameter    ap_ST_fsm_state47 = 66'd70368744177664;
parameter    ap_ST_fsm_state48 = 66'd140737488355328;
parameter    ap_ST_fsm_state49 = 66'd281474976710656;
parameter    ap_ST_fsm_state50 = 66'd562949953421312;
parameter    ap_ST_fsm_state51 = 66'd1125899906842624;
parameter    ap_ST_fsm_state52 = 66'd2251799813685248;
parameter    ap_ST_fsm_state53 = 66'd4503599627370496;
parameter    ap_ST_fsm_state54 = 66'd9007199254740992;
parameter    ap_ST_fsm_state55 = 66'd18014398509481984;
parameter    ap_ST_fsm_state56 = 66'd36028797018963968;
parameter    ap_ST_fsm_state57 = 66'd72057594037927936;
parameter    ap_ST_fsm_state58 = 66'd144115188075855872;
parameter    ap_ST_fsm_state59 = 66'd288230376151711744;
parameter    ap_ST_fsm_state60 = 66'd576460752303423488;
parameter    ap_ST_fsm_state61 = 66'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 66'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 66'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 66'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 66'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 66'd36893488147419103232;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] length_r;
output  [31:0] kSQI;
output   kSQI_ap_vld;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg kSQI_ap_vld;

wire   [0:0] ap_local_deadlock;
 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [65:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] data;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
wire   [31:0] grp_fu_159_p2;
reg   [31:0] reg_169;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state50;
reg   [61:0] trunc_ln_reg_237;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln12_fu_195_p2;
reg   [0:0] icmp_ln12_reg_255;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_165_p1;
reg   [31:0] conv_i_i_reg_259;
wire   [30:0] trunc_ln12_fu_200_p1;
reg   [30:0] trunc_ln12_reg_265;
wire   [31:0] grp_fu_154_p2;
reg   [31:0] mul3_i_reg_277;
wire    ap_CS_fsm_state34;
reg   [10:0] buff_address0;
reg    buff_ce0;
reg    buff_we0;
wire   [31:0] buff_q0;
wire    grp_overlay_fea_Pipeline_1_fu_130_ap_start;
wire    grp_overlay_fea_Pipeline_1_fu_130_ap_done;
wire    grp_overlay_fea_Pipeline_1_fu_130_ap_idle;
wire    grp_overlay_fea_Pipeline_1_fu_130_ap_ready;
wire    grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWVALID;
wire   [63:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWADDR;
wire   [0:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWID;
wire   [31:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWLEN;
wire   [2:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWSIZE;
wire   [1:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWBURST;
wire   [1:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWLOCK;
wire   [3:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWCACHE;
wire   [2:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWPROT;
wire   [3:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWQOS;
wire   [3:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWREGION;
wire   [0:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWUSER;
wire    grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WVALID;
wire   [31:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WDATA;
wire   [3:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WSTRB;
wire    grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WLAST;
wire   [0:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WID;
wire   [0:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WUSER;
wire    grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARVALID;
wire   [63:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARADDR;
wire   [0:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARID;
wire   [31:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARLEN;
wire   [2:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARSIZE;
wire   [1:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARBURST;
wire   [1:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARLOCK;
wire   [3:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARCACHE;
wire   [2:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARPROT;
wire   [3:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARQOS;
wire   [3:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARREGION;
wire   [0:0] grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARUSER;
wire    grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_RREADY;
wire    grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_BREADY;
wire   [10:0] grp_overlay_fea_Pipeline_1_fu_130_buff_address0;
wire    grp_overlay_fea_Pipeline_1_fu_130_buff_ce0;
wire    grp_overlay_fea_Pipeline_1_fu_130_buff_we0;
wire   [31:0] grp_overlay_fea_Pipeline_1_fu_130_buff_d0;
wire    grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start;
wire    grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_done;
wire    grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_idle;
wire    grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_ready;
wire   [10:0] grp_overlay_fea_Pipeline_Loop_mean_fu_138_buff_address0;
wire    grp_overlay_fea_Pipeline_Loop_mean_fu_138_buff_ce0;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_mean_fu_138_sum_out;
wire    grp_overlay_fea_Pipeline_Loop_mean_fu_138_sum_out_ap_vld;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_din0;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_din1;
wire   [0:0] grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_opcode;
wire    grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_ce;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_done;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_idle;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_ready;
wire   [10:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_buff_address0;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_buff_ce0;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_m4_out;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_m4_out_ap_vld;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_m2_out;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_m2_out_ap_vld;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_din0;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_din1;
wire   [1:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_opcode;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_ce;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_din0;
wire   [31:0] grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_din1;
wire    grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_ce;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [0:0] gmem_ARID;
reg   [31:0] gmem_ARLEN;
reg   [2:0] gmem_ARSIZE;
reg   [1:0] gmem_ARBURST;
reg   [1:0] gmem_ARLOCK;
reg   [3:0] gmem_ARCACHE;
reg   [2:0] gmem_ARPROT;
reg   [3:0] gmem_ARQOS;
reg   [3:0] gmem_ARREGION;
reg   [0:0] gmem_ARUSER;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [8:0] gmem_RFIFONUM;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg   [31:0] ap_phi_mux_m4_0_lcssa_i_phi_fu_110_p4;
reg   [31:0] m4_0_lcssa_i_reg_106;
wire    ap_CS_fsm_state31;
wire   [31:0] ap_phi_mux_m2_0_lcssa_i_phi_fu_122_p4;
reg   [31:0] m2_0_lcssa_i_reg_118;
reg    grp_overlay_fea_Pipeline_1_fu_130_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start_reg;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire  signed [63:0] sext_ln43_fu_185_p1;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state66;
reg   [31:0] grp_fu_154_p0;
reg   [31:0] grp_fu_154_p1;
reg   [31:0] grp_fu_159_p0;
reg   [31:0] grp_fu_159_p1;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state51;
reg    grp_fu_154_ce;
reg    grp_fu_165_ce;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [31:0] grp_fu_282_p2;
reg   [31:0] grp_fu_282_p0;
reg   [31:0] grp_fu_282_p1;
reg   [1:0] grp_fu_282_opcode;
reg    grp_fu_282_ce;
reg   [65:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 66'd1;
#0 grp_overlay_fea_Pipeline_1_fu_130_ap_start_reg = 1'b0;
#0 grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start_reg = 1'b0;
#0 grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start_reg = 1'b0;
end

overlay_fea_buff_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2000 ),
    .AddressWidth( 11 ))
buff_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buff_address0),
    .ce0(buff_ce0),
    .we0(buff_we0),
    .d0(grp_overlay_fea_Pipeline_1_fu_130_buff_d0),
    .q0(buff_q0)
);

overlay_fea_overlay_fea_Pipeline_1 grp_overlay_fea_Pipeline_1_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_overlay_fea_Pipeline_1_fu_130_ap_start),
    .ap_done(grp_overlay_fea_Pipeline_1_fu_130_ap_done),
    .ap_idle(grp_overlay_fea_Pipeline_1_fu_130_ap_idle),
    .ap_ready(grp_overlay_fea_Pipeline_1_fu_130_ap_ready),
    .m_axi_gmem_AWVALID(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln43(trunc_ln_reg_237),
    .buff_address0(grp_overlay_fea_Pipeline_1_fu_130_buff_address0),
    .buff_ce0(grp_overlay_fea_Pipeline_1_fu_130_buff_ce0),
    .buff_we0(grp_overlay_fea_Pipeline_1_fu_130_buff_we0),
    .buff_d0(grp_overlay_fea_Pipeline_1_fu_130_buff_d0)
);

overlay_fea_overlay_fea_Pipeline_Loop_mean grp_overlay_fea_Pipeline_Loop_mean_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start),
    .ap_done(grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_done),
    .ap_idle(grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_idle),
    .ap_ready(grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_ready),
    .trunc_ln1(trunc_ln12_reg_265),
    .buff_address0(grp_overlay_fea_Pipeline_Loop_mean_fu_138_buff_address0),
    .buff_ce0(grp_overlay_fea_Pipeline_Loop_mean_fu_138_buff_ce0),
    .buff_q0(buff_q0),
    .sum_out(grp_overlay_fea_Pipeline_Loop_mean_fu_138_sum_out),
    .sum_out_ap_vld(grp_overlay_fea_Pipeline_Loop_mean_fu_138_sum_out_ap_vld),
    .grp_fu_282_p_din0(grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_din0),
    .grp_fu_282_p_din1(grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_din1),
    .grp_fu_282_p_opcode(grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_opcode),
    .grp_fu_282_p_dout0(grp_fu_282_p2),
    .grp_fu_282_p_ce(grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_ce)
);

overlay_fea_overlay_fea_Pipeline_Loop_kur grp_overlay_fea_Pipeline_Loop_kur_fu_145(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start),
    .ap_done(grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_done),
    .ap_idle(grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_idle),
    .ap_ready(grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_ready),
    .trunc_ln1(trunc_ln12_reg_265),
    .buff_address0(grp_overlay_fea_Pipeline_Loop_kur_fu_145_buff_address0),
    .buff_ce0(grp_overlay_fea_Pipeline_Loop_kur_fu_145_buff_ce0),
    .buff_q0(buff_q0),
    .div_i_i(reg_169),
    .m4_out(grp_overlay_fea_Pipeline_Loop_kur_fu_145_m4_out),
    .m4_out_ap_vld(grp_overlay_fea_Pipeline_Loop_kur_fu_145_m4_out_ap_vld),
    .m2_out(grp_overlay_fea_Pipeline_Loop_kur_fu_145_m2_out),
    .m2_out_ap_vld(grp_overlay_fea_Pipeline_Loop_kur_fu_145_m2_out_ap_vld),
    .grp_fu_282_p_din0(grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_din0),
    .grp_fu_282_p_din1(grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_din1),
    .grp_fu_282_p_opcode(grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_opcode),
    .grp_fu_282_p_dout0(grp_fu_282_p2),
    .grp_fu_282_p_ce(grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_ce),
    .grp_fu_154_p_din0(grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_din0),
    .grp_fu_154_p_din1(grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_din1),
    .grp_fu_154_p_dout0(grp_fu_154_p2),
    .grp_fu_154_p_ce(grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_ce)
);

overlay_fea_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .data(data),
    .ap_local_deadlock(ap_local_deadlock)
);

overlay_fea_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(gmem_ARID),
    .I_ARLEN(gmem_ARLEN),
    .I_ARSIZE(gmem_ARSIZE),
    .I_ARLOCK(gmem_ARLOCK),
    .I_ARCACHE(gmem_ARCACHE),
    .I_ARQOS(gmem_ARQOS),
    .I_ARPROT(gmem_ARPROT),
    .I_ARUSER(gmem_ARUSER),
    .I_ARBURST(gmem_ARBURST),
    .I_ARREGION(gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

overlay_fea_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_154_p0),
    .din1(grp_fu_154_p1),
    .ce(grp_fu_154_ce),
    .dout(grp_fu_154_p2)
);

overlay_fea_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_159_p0),
    .din1(grp_fu_159_p1),
    .ce(1'b1),
    .dout(grp_fu_159_p2)
);

overlay_fea_sitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_6_no_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(length_r),
    .ce(grp_fu_165_ce),
    .dout(grp_fu_165_p1)
);

overlay_fea_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_282_p0),
    .din1(grp_fu_282_p1),
    .opcode(grp_fu_282_opcode),
    .ce(grp_fu_282_ce),
    .dout(grp_fu_282_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_overlay_fea_Pipeline_1_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_overlay_fea_Pipeline_1_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_overlay_fea_Pipeline_1_fu_130_ap_ready == 1'b1)) begin
            grp_overlay_fea_Pipeline_1_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state29)) begin
            grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start_reg <= 1'b1;
        end else if ((grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_ready == 1'b1)) begin
            grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_ready == 1'b1)) begin
            grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_overlay_fea_Pipeline_1_fu_130_ap_done == 1'b1) & (icmp_ln12_fu_195_p2 == 1'd0))) begin
        m2_0_lcssa_i_reg_118 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state31) & (icmp_ln12_reg_255 == 1'd1))) begin
        m2_0_lcssa_i_reg_118 <= grp_overlay_fea_Pipeline_Loop_kur_fu_145_m2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_overlay_fea_Pipeline_1_fu_130_ap_done == 1'b1) & (icmp_ln12_fu_195_p2 == 1'd0))) begin
        m4_0_lcssa_i_reg_106 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state31) & (icmp_ln12_reg_255 == 1'd1))) begin
        m4_0_lcssa_i_reg_106 <= grp_overlay_fea_Pipeline_Loop_kur_fu_145_m4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        conv_i_i_reg_259 <= grp_fu_165_p1;
        icmp_ln12_reg_255 <= icmp_ln12_fu_195_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        mul3_i_reg_277 <= grp_fu_154_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state28))) begin
        reg_169 <= grp_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln12_fu_195_p2 == 1'd1))) begin
        trunc_ln12_reg_265 <= trunc_ln12_fu_200_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_237 <= {{data[63:2]}};
    end
end

always @ (*) begin
    if ((grp_overlay_fea_Pipeline_1_fu_130_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_done == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) & (icmp_ln12_reg_255 == 1'd1))) begin
        ap_phi_mux_m4_0_lcssa_i_phi_fu_110_p4 = grp_overlay_fea_Pipeline_Loop_kur_fu_145_m4_out;
    end else begin
        ap_phi_mux_m4_0_lcssa_i_phi_fu_110_p4 = m4_0_lcssa_i_reg_106;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        buff_address0 = grp_overlay_fea_Pipeline_Loop_kur_fu_145_buff_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buff_address0 = grp_overlay_fea_Pipeline_Loop_mean_fu_138_buff_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buff_address0 = grp_overlay_fea_Pipeline_1_fu_130_buff_address0;
    end else begin
        buff_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        buff_ce0 = grp_overlay_fea_Pipeline_Loop_kur_fu_145_buff_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buff_ce0 = grp_overlay_fea_Pipeline_Loop_mean_fu_138_buff_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buff_ce0 = grp_overlay_fea_Pipeline_1_fu_130_buff_ce0;
    end else begin
        buff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buff_we0 = grp_overlay_fea_Pipeline_1_fu_130_buff_we0;
    end else begin
        buff_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARADDR = sext_ln43_fu_185_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARADDR = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARBURST = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARBURST;
    end else begin
        gmem_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARCACHE = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARCACHE;
    end else begin
        gmem_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARID = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARID;
    end else begin
        gmem_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARLEN = 32'd2000;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLEN = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLOCK = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARLOCK;
    end else begin
        gmem_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARPROT = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARPROT;
    end else begin
        gmem_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARQOS = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARQOS;
    end else begin
        gmem_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARREGION = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARREGION;
    end else begin
        gmem_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARSIZE = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARSIZE;
    end else begin
        gmem_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARUSER = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARUSER;
    end else begin
        gmem_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARVALID = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_RREADY = grp_overlay_fea_Pipeline_1_fu_130_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_154_ce = grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_ce;
    end else begin
        grp_fu_154_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_154_p0 = grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_154_p0 = conv_i_i_reg_259;
    end else begin
        grp_fu_154_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_154_p1 = grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_154_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_154_p1 = ap_phi_mux_m4_0_lcssa_i_phi_fu_110_p4;
    end else begin
        grp_fu_154_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_159_p0 = reg_169;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_159_p0 = mul3_i_reg_277;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_159_p0 = grp_overlay_fea_Pipeline_Loop_mean_fu_138_sum_out;
    end else begin
        grp_fu_159_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_159_p1 = m2_0_lcssa_i_reg_118;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_159_p1 = ap_phi_mux_m2_0_lcssa_i_phi_fu_122_p4;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_159_p1 = conv_i_i_reg_259;
    end else begin
        grp_fu_159_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state10) & (grp_overlay_fea_Pipeline_1_fu_130_ap_done == 1'b1)))) begin
        grp_fu_165_ce = 1'b1;
    end else begin
        grp_fu_165_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_282_ce = grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_282_ce = grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_ce;
    end else begin
        grp_fu_282_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_282_opcode = grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_282_opcode = grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_opcode;
    end else begin
        grp_fu_282_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_282_p0 = grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_282_p0 = grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_din0;
    end else begin
        grp_fu_282_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_282_p1 = grp_overlay_fea_Pipeline_Loop_kur_fu_145_grp_fu_282_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_282_p1 = grp_overlay_fea_Pipeline_Loop_mean_fu_138_grp_fu_282_p_din1;
    end else begin
        grp_fu_282_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        kSQI_ap_vld = 1'b1;
    end else begin
        kSQI_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_overlay_fea_Pipeline_1_fu_130_ap_done == 1'b1) & (icmp_ln12_fu_195_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else if (((1'b1 == ap_CS_fsm_state10) & (grp_overlay_fea_Pipeline_1_fu_130_ap_done == 1'b1) & (icmp_ln12_fu_195_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((1'b1 == ap_CS_fsm_state30) & (grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

assign ap_phi_mux_m2_0_lcssa_i_phi_fu_122_p4 = m2_0_lcssa_i_reg_118;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_overlay_fea_Pipeline_1_fu_130_ap_start = grp_overlay_fea_Pipeline_1_fu_130_ap_start_reg;

assign grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start = grp_overlay_fea_Pipeline_Loop_kur_fu_145_ap_start_reg;

assign grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start = grp_overlay_fea_Pipeline_Loop_mean_fu_138_ap_start_reg;

assign icmp_ln12_fu_195_p2 = (($signed(length_r) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign kSQI = grp_fu_159_p2;

assign sext_ln43_fu_185_p1 = $signed(trunc_ln_reg_237);

assign trunc_ln12_fu_200_p1 = length_r[30:0];

endmodule //overlay_fea
